baseurl         = "https://elated-blackwell-51e103.netlify.com/"
theme           = "casper-two"
languageCode    = "jp-JP"
disqusShortname = "https-elated-blackwell-51e103-netlify-com."
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
title       = "ITエンジニアりんごくの技術ブログ"

[params]
  title       = "ITエンジニアりんごくの技術ブログ"
  subtitle    = "ITエンジニアりんごくの技術ブログ"
  copyright   = "© 2019"

  cover       = "img/blog-cover.jpg"
  description = "Webエンジニアりんごくの日々の活動記録。学んだ技術についてのアウトプットや読んだ書籍の紹介などを行います。"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "RinGoku98"
  githubName = "RinGoku"
  mediumName = ""
  qiitaName = "RinGoku"

  logo = "hugo-logo.png"
  orgName = "りんごく"
  orgWebsite = "https://www.telematika.org"
  orgDescription = ""

  showSupport = true

  author = "りんごく"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "東京品川区"
  authorWebsite = "https://ringoku.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "カテゴリー"
  url = "/categories/"
  weight = 99


